SELECT SYSDATE + 15 AS NEW_DATE FROM DUAL;

SELECT 
    ADD_MONTHS(SYSDATE, 5) AS ADD_5_MONTHS,
    ADD_MONTHS(SYSDATE, -5) AS SUB_5_MONTHS
FROM DUAL;

SELECT ASCII('M') AS ASCII_VALUE FROM DUAL;

SELECT 
    CHR(67) AS C1,
    CHR(65) AS C2,
    CHR(84) AS C3
FROM DUAL;

SELECT LAST_DAY(SYSDATE) AS LAST_DATE FROM DUAL;

SELECT SYSDATE - TO_DATE('20-05-2015','DD-MM-YYYY') AS DAYS_DIFF
FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('03-03-2016','DD-MM-YYYY')) 
AS MONTH_DIFF
FROM DUAL;

SELECT INSTR('corporate floor', 'or', 3, 2) AS POSITION
FROM DUAL;

SELECT INITCAP('marwadi university') AS FORMATTED_TEXT
FROM DUAL;

SELECT 
    USER AS USER_NAME,
    USERENV('SESSIONID') AS USER_ID
FROM DUAL;
