
CREATE TABLE DEPOSIT (
    ACTNO NUMBER,
    CNAME VARCHAR2(20),
    BNAME VARCHAR2(20),
    AMOUNT NUMBER(10,2)
);

INSERT INTO DEPOSIT VALUES (101,'ANIL','VRCE',1000);
INSERT INTO DEPOSIT VALUES (102,'SUNIL','AJNI',5000);
INSERT INTO DEPOSIT VALUES (103,'MEHUL','KAROLBAGH',3500);


CREATE TABLE BORROW (
    LOANNO NUMBER,
    CNAME VARCHAR2(20),
    BNAME VARCHAR2(20),
    AMOUNT NUMBER(10,2)
);

INSERT INTO BORROW VALUES (201,'ANIL','VRCE',1000);
INSERT INTO BORROW VALUES (206,'MEHUL','AJNI',5000);
INSERT INTO BORROW VALUES (311,'SUNIL','KAROLBAGH',3000);


CREATE TABLE CUSTOMERS (
    CNAME VARCHAR2(20),
    CITY VARCHAR2(20)
);

INSERT INTO CUSTOMERS VALUES ('ANIL','NAGPUR');
INSERT INTO CUSTOMERS VALUES ('SUNIL','DELHI');
INSERT INTO CUSTOMERS VALUES ('MEHUL','BARODA');

CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER,
    EMP_NAME VARCHAR2(20),
    EMP_SAL NUMBER,
    EMP_COMM NUMBER,
    DEPT_NO NUMBER
);

INSERT INTO EMPLOYEE VALUES (101,'SMITH',800,0,20);
INSERT INTO EMPLOYEE VALUES (102,'SNEHAL',1600,300,25);
INSERT INTO EMPLOYEE VALUES (103,'ADAMA',1100,0,20);
INSERT INTO EMPLOYEE VALUES (104,'AMAN',3000,0,15);
INSERT INTO EMPLOYEE VALUES (105,'ANITA',5000,500,10);
INSERT INTO EMPLOYEE VALUES (106,'SNEHA',2450,245,10);
INSERT INTO EMPLOYEE VALUES (107,'ANAMIKA',2975,0,30);

select*from DEPOSIT;
select*from BORROW;
select*from CUSTOMERS;
select*from EMPLOYEE;

SELECT SUM(AMOUNT) AS TOTAL_DEPOSIT FROM DEPOSIT;

SELECT SUM(AMOUNT) AS TOTAL_LOAN 
FROM BORROW
WHERE BNAME = 'KAROLBAGH';

SELECT MAX(AMOUNT) AS MAX_LOAN
FROM BORROW
WHERE BNAME = 'VRCE';

SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS;

SELECT COUNT(DISTINCT CITY) AS TOTAL_CITIES 
FROM CUSTOMERS;

CREATE TABLE SUPPLIER AS
SELECT * FROM EMPLOYEE;

CREATE TABLE SUP1 AS
SELECT EMP_NO, EMP_NAME FROM EMPLOYEE;

CREATE TABLE SUP2 AS
SELECT * FROM EMPLOYEE WHERE 1=2;

INSERT INTO SUP2
SELECT * FROM EMPLOYEE
WHERE LENGTH(EMP_NAME)=5
AND SUBSTR(EMP_NAME,2,1)='N';

DELETE FROM SUP1;

DELETE FROM SUPPLIER WHERE EMP_NO = 103;

ALTER TABLE SUP2 RENAME TO SUPLIER_TWO;

DROP TABLE SUP1;

UPDATE EMPLOYEE
SET DEPT_NO = 10
WHERE SUBSTR(EMP_NAME,2,1) = 'M';

UPDATE EMPLOYEE
SET EMP_NAME = 'NEWNAME'
WHERE EMP_NO = 103;


